export const RECEIVE_INDEX_ADS = 'RECEIVE_INDEX_ADS';

export const CLOSE_DOWNLOAD_HINT = 'CLOSE_DOWNLOAD_HINT';

export const UPDATE_SESSION_ID = 'UPDATE_SESSION_ID';

export const UPDATE_USER_INFO = 'UPDATE_USER_INFO';

export const LOGOUT_USER = 'LOGOUT_USER';
